            if piece == "n":
                if kq == "w_king" or kq == "b_king":
                    x_king, y_king = self.cc.chess_to_robot(kq_position[kq])
                    self.moving(x_king, y_king, 150)
                    self.moving(x_king, y_king, self.piece_height["k"], 80)
                    self.arm.close_lite6_gripper()
                    time.sleep(1)
                    self.moving(x_king, y_king, 150)
                    self.moving(110, 0, 150)
                    self.moving(110, 0, self.piece_height["k"], 80)
                    self.arm.open_lite6_gripper()
                    time.sleep(1)
                    self.arm.stop_lite6_gripper()
                    self.moving(x, y, 150, yaw=-90)
                    self.moving(x, y, self.piece_height[piece], 80, yaw=-90)
                    self.arm.close_lite6_gripper()
                    time.sleep(1)
                    self.moving(x, y, self.piece_height[piece], 80, yaw=0)
                    self.arm.open_lite6_gripper()
                    time.sleep(1)
                    self.arm.stop_lite6_gripper()
                    self.moving(110, 0, 150)
                    self.moving(110, 0, self.piece_height["k"], 80)
                    self.arm.close_lite6_gripper()
                    time.sleep(1)
                    self.moving(110, 0, 150)
                    self.moving(x_king, y_king, 150)
                    self.moving(x_king, y_king, self.piece_height["k"], 80)
                    self.arm.open_lite6_gripper()
                    time.sleep(1)
                    self.arm.stop_lite6_gripper()
                    self.moving(x_king, y_king, 150)